<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="citymanagement" nsURI="http://citymanagement/1.0" nsPrefix="citymanagement">
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportationManagement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CityTrafficManagement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CityWeatherInformationManagement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CityWasteDisposalManagement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CitizenManagement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CityInfrastructureManagement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CityEnergyManagement"/>
</ecore:EPackage>
