<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="citywastedisposalinfrastructure" nsURI="http://citywastedisposalinfrastructure/1.0"
    nsPrefix="citywastedisposalinfrastructure">
  <eClassifiers xsi:type="ecore:EClass" name="Waste" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Organic" eSuperTypes="#//Waste"/>
  <eClassifiers xsi:type="ecore:EClass" name="Plastic" eSuperTypes="#//Recyclable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Metal" eSuperTypes="#//Recyclable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Recyclable" eSuperTypes="#//Waste"/>
  <eClassifiers xsi:type="ecore:EClass" name="Glass" eSuperTypes="#//Recyclable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Miscellaneous" eSuperTypes="#//Waste"/>
  <eClassifiers xsi:type="ecore:EClass" name="WasteCollection" abstract="true" interface="true">
    <eOperations name="getWasteType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrivateBin" eSuperTypes="#//WasteCollection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="waste" eType="#//Waste"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="publicBin" eSuperTypes="#//WasteCollection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="waste" eType="#//Waste"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GarbageTruck">
    <eStructuralFeatures xsi:type="ecore:EReference" name="schedule" eType="#//CollectionSchedule"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collectionRouteName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="route" upperBound="-1"
        eType="#//Location" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionSchedule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nextCollection" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastCollection" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nextCollectionType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastCollectionType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WasteDisposal">
    <eStructuralFeatures xsi:type="ecore:EReference" name="disposalCenter" eType="#//DisposalCenter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionAndDisposal">
    <eStructuralFeatures xsi:type="ecore:EReference" name="disposalCenter" eType="#//DisposalCenter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="route" upperBound="-1"
        eType="#//Location" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DisposalCenter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wasteType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="latitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
