<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="citytransportinventory" nsURI="http://citytransportinventory/1.0"
    nsPrefix="citytransportinventory">
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle" abstract="true" eSuperTypes="#//Maintainable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fuelStats" eType="#//Fuel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="registration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seatingCapacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cycleCapacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="physicallyHandicappedSupport"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastMaintanance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nextMaintanence" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bus" eSuperTypes="#//Vehicle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="busType" eType="#//BusType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Train" eSuperTypes="#//Vehicle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trainType" eType="#//TrainType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tram" eSuperTypes="#//Vehicle"/>
  <eClassifiers xsi:type="ecore:EClass" name="Station" abstract="true">
    <eOperations name="getStationLocation" eType="#//Location"/>
    <eOperations name="getAllConnections"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" eType="#//Location"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusStation" eSuperTypes="#//Station"/>
  <eClassifiers xsi:type="ecore:EClass" name="TrainStation" eSuperTypes="#//Station"/>
  <eClassifiers xsi:type="ecore:EClass" name="TramStation" eSuperTypes="#//Station"/>
  <eClassifiers xsi:type="ecore:EClass" name="Route" abstract="true">
    <eOperations name="getAllStationsAfterStation" eType="#//Station"/>
    <eOperations name="getEndStation" eType="#//Station"/>
    <eOperations name="getStartStation" eType="#//Station"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" upperBound="-1"
        eType="#//Station" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedVehicles" upperBound="-1"
        eType="#//Vehicle" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusRoute" eSuperTypes="#//Route"/>
  <eClassifiers xsi:type="ecore:EClass" name="TrainRoute" eSuperTypes="#//Route"/>
  <eClassifiers xsi:type="ecore:EClass" name="TramRoute" eSuperTypes="#//Route"/>
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="latitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ticket" abstract="true" interface="true">
    <eOperations name="getvalidity"/>
    <eOperations name="getCost"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusTicket" eSuperTypes="#//Ticket">
    <eStructuralFeatures xsi:type="ecore:EReference" name="route" eType="#//Route"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrainTicket" eSuperTypes="#//Ticket">
    <eStructuralFeatures xsi:type="ecore:EReference" name="route" eType="#//Route"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TramTicket" eSuperTypes="#//Ticket">
    <eStructuralFeatures xsi:type="ecore:EReference" name="route" eType="#//Route"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fuel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fuelType" eType="#//FuelType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Petrol"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FuelType">
    <eLiterals name="PETROL"/>
    <eLiterals name="DIESEL" value="1"/>
    <eLiterals name="ELECTRIC" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TrainType">
    <eLiterals name="RB"/>
    <eLiterals name="SB" value="1"/>
    <eLiterals name="UB" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BusType">
    <eLiterals name="LONG"/>
    <eLiterals name="SHORT" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionInfrastructure" abstract="true"
      eSuperTypes="#//Maintainable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nextMaintanence" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastMaintanence" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Road" eSuperTypes="#//ConnectionInfrastructure"/>
  <eClassifiers xsi:type="ecore:EClass" name="Rail" eSuperTypes="#//ConnectionInfrastructure"/>
  <eClassifiers xsi:type="ecore:EClass" name="TramTracks" eSuperTypes="#//ConnectionInfrastructure"/>
  <eClassifiers xsi:type="ecore:EClass" name="Maintainable" abstract="true" interface="true">
    <eOperations name="getLastMaintenanceDate"/>
    <eOperations name="getNextMaintenance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle" abstract="true" eSuperTypes="#//Maintainable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fuelStats" eType="#//Fuel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="registration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seatingCapacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cycleCapacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="physicallyHandicappedSupport"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastMaintanance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nextMaintanence" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
</ecore:EPackage>
