<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="citytrafficbusiness" nsURI="http://citytrafficbusiness/1.0"
    nsPrefix="citytrafficbusiness">
  <eClassifiers xsi:type="ecore:EClass" name="VehicleOwner" eSuperTypes="#//Addressable">
    <eOperations name="buyPass"/>
    <eOperations name="getAllPasses" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eOperations name="payFineForViolation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="passes" upperBound="-1"
        eType="#//ParkingPass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="violationFine" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Addressable" abstract="true" interface="true">
    <eOperations name="getStreet"/>
    <eOperations name="getCity"/>
    <eOperations name="getPhoneNumber"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Employee" eSuperTypes="#//Addressable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="salary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="workAssignment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParkingPass" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Violation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="violator" eType="#//VehicleOwner"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="details" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClass0"/>
  <eClassifiers xsi:type="ecore:EClass" name="Traffic" eSuperTypes="#//Violation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="violation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parking" eSuperTypes="#//Violation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="officerIncharge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
