<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="citytrafficinfrastructure" nsURI="http://citytrafficinfrastructure/1.0"
    nsPrefix="citytrafficinfrastructure">
  <eClassifiers xsi:type="ecore:EClass" name="Infrastructure" abstract="true" interface="true">
    <eOperations name="isActive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="getInfrastructureLocation" eType="#//Location"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParkingInfrastructure" abstract="true"
      eSuperTypes="#//Infrastructure">
    <eOperations name="getLocation" eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" eType="#//Location"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrafficInfrastructure" abstract="true"
      eSuperTypes="#//Infrastructure">
    <eOperations name="activate"/>
    <eOperations name="deactivate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" eType="#//Location"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParkingLot" eSuperTypes="#//ParkingInfrastructure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalCapacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emptyLots" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublicParking" eSuperTypes="#//ParkingInfrastructure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parkingCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="occupied" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EDataType0"/>
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="latitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Surveillance" abstract="true" eSuperTypes="#//TrafficInfrastructure"/>
  <eClassifiers xsi:type="ecore:EClass" name="Control" abstract="true" eSuperTypes="#//TrafficInfrastructure"/>
  <eClassifiers xsi:type="ecore:EClass" name="EClass0"/>
  <eClassifiers xsi:type="ecore:EClass" name="EClass1"/>
  <eClassifiers xsi:type="ecore:EClass" name="EClass2"/>
  <eClassifiers xsi:type="ecore:EClass" name="TrafficCamera" eSuperTypes="#//Surveillance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="storage" eType="#//DataStorage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpeedCam" eSuperTypes="#//Surveillance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="storage" eType="#//DataStorage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Signal" eSuperTypes="#//Control">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//Control"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataStorage">
    <eOperations name="store"/>
    <eOperations name="getStoredData"/>
  </eClassifiers>
</ecore:EPackage>
