<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="city" nsURI="http://city/1.0" nsPrefix="city">
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="driver" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fuelType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seats" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="physicallyHandicappedSupport"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cycles" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Train" eSuperTypes="#//Vehicle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trainType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toilets" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bus" eSuperTypes="#//Vehicle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="busType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Stops"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tram" eSuperTypes="#//Vehicle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stop" instanceTypeName="Stop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="StopLocation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EAttribute0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EAttribute1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrainStation" eSuperTypes="#//Stop"/>
  <eClassifiers xsi:type="ecore:EClass" name="BusStop" eSuperTypes="#//Stop"/>
  <eClassifiers xsi:type="ecore:EClass" name="TramStop" eSuperTypes="#//Stop"/>
  <eClassifiers xsi:type="ecore:EClass" name="User" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Traveler" eSuperTypes="#//User">
    <eStructuralFeatures xsi:type="ecore:EReference" name="details"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Admin" eSuperTypes="#//User">
    <eStructuralFeatures xsi:type="ecore:EReference" name="details"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FuelType"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FuelType">
    <eLiterals name="PETROL"/>
    <eLiterals name="DIESEL" value="1"/>
    <eLiterals name="ELECTRIC" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TrainType">
    <eLiterals name="RB" value="1"/>
    <eLiterals name="UB" value="2"/>
    <eLiterals name="SB"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BusType">
    <eLiterals name="SHORT"/>
    <eLiterals name="LONG" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="StopName"/>
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="latitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="l" eType="#//Stop"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Time" instanceTypeName="Calendar"/>
  <eClassifiers xsi:type="ecore:EClass" name="Road"/>
  <eClassifiers xsi:type="ecore:EClass" name="Road"/>
  <eClassifiers xsi:type="ecore:EClass" name="Rail"/>
</ecore:EPackage>
